### ISSUE TITLE
J matrices do not download with setup.py develop

### ISSUE THREAD

**Issue by bkmi** [AMLab-Amsterdam/lie_learn#10]
Both `python setup.py develop` and `pip install -e .` do not download the J matrices file from google drive. Not terrible for someone who wants to open this repo in develop mode, but worth mentioning.

I will fix it later if I need it.

**Comment by mys007** [comment]
Indeed, the installation seems to be broken because there instead of downloading J_dense_0-278.npy , only the HTML page corresponding to the warning 

```
Google Drive can't scan this file for viruses.

J_dense_0-278.npy (221M) is too large for Google to scan for viruses. Would you still like to download this file?
```

This is then demonstrated in the code with `OSError: Failed to interpret file '....../lib/python3.6/site-packages/lie_learn/representations/SO3/pinchon_hoggan/J_dense_0-278.npy' as a pickle`

**Comment by mariogeiger** [comment]
Now the file is hosted on github
