### ISSUE TITLE
lie_learn fail to be installed in Conda with Python 3.6

### ISSUE THREAD

**Issue by jiapei100** [AMLab-Amsterdam/lie_learn#5]
Check [conda lie_learn fail to install](https://pastebin.com/eRdPAahD)

**Comment by antigol** [comment]
Does it work if you install it manually ?
1. clone the repository with `git clone`
2. run `python setup.py install`

**Comment by FreesiaLikesPomelo** [comment]
> Does it work if you install it manually ?
> 
>     1. clone the repository with `git clone`
> 
>     2. run `python setup.py install`

I tried manually installation as you recommend.
But it still failed to be installed with the same  error: 

running install_scripts
Start to download file ID 0B5e7DAOiLEZwSkdfXzBYT29Nc3c from google drive into /home/hanyu/anaconda3/envs/AMLab_lie/lib/python3.6/site-packages/lie_learn/representations/SO3/pinchon_hoggan/J_dense_0-278.npy
Error during the download
error: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=0B5e7DAOiLEZwSkdfXzBYT29Nc3c (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff9df64dd30>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

**Comment by mariogeiger** [comment]
The installation script has to download a file from google drive

**Comment by EricPengShuai** [comment]
@mariogeiger I tried but error occurred.https://github.com/AMLab-Amsterdam/lie_learn/issues/5#issuecomment-385181900
```python
lie_learn\groups\SO3.pyx:1:0: 'lie_learn\groups\SO3' is not a valid module name
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    extensions = cythonize(extensions)
  File "C:\Users\peng\anaconda3\envs\pytorch_1.8\lib\site-packages\Cython\Build\Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "C:\Users\peng\anaconda3\envs\pytorch_1.8\lib\site-packages\Cython\Build\Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: lie_learn\groups\SO3.pyx
```

**Comment by NewConn** [comment]
Is there any other download address for it? Like github or huggingface? I don't have network hard drive (storage) access on my company computer.
